blog/urls.py
from django.urls import path

from blog import views


urlpatterns = [
	path('tagify_query/', views.tagify_query, name='tagify_query'),
]

newsletter/urls.py
from . import views
from django.urls import path
urlpatterns = [
	path('', views.newsletter_base, name='newsletter_base'),
	path('popup/', views.popup, name='popup'),
	path('popup_js/', views.popup_js, name='popup_js'),
	path('subscribe/', views.subscribe, name='subscribe'),
	path('unsubscribe/<encoded_email>/', views.unsubscribe_view, name='unsubscribe'),
]

webshop/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from home.views import home
from search import views as search_views

urlpatterns = i18n_patterns(
	path('', home, name=''),
	path('i18n/', include('django.conf.urls.i18n')),
	path('django-admin/', admin.site.urls),
	path('admin/', include(wagtailadmin_urls)),
	path('documents/', include(wagtaildocs_urls)),
	path('search/', search_views.search, name='search'),
	path('password-reset/complete/', 
		auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
		name='password_reset_complete'),
	path(_('home/'), include(('home.urls', 'home'), namespace='home')),
	path(_('account/'), include(('account.urls', 'account'), namespace='account')),
	path(_('blog/'), include(('blog.urls', 'blog'), namespace='blog')),
	path(_('cart/'), include(('cart.urls', 'cart'), namespace='cart')),
	path(_('contact/'), include(('contact.urls', 'contact'), namespace='contact')),
	path(_('coupon/'), include(('coupon.urls', 'coupon'), namespace='coupon')),
	path(_('newsletter/'), include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
	path(_('order/'), include(('order.urls', 'order'), namespace='order')),
	path(_('shop/'), include(('shop.urls', 'shop'), namespace='shop')),
	path(_('winwheel/'), include(('winwheel.urls', 'winwheel'), namespace='winwheel')),
	path('rosetta/', include('rosetta.urls')),
)



if settings.DEBUG:
	import debug_toolbar
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns = urlpatterns + i18n_patterns(
	# For anything not caught by a more specific rule above, hand over to
	# Wagtail's page serving mechanism. This should be the last pattern in
	# the list:
	path('', include(wagtail_urls)),

	# Alternatively, if you want Wagtail pages to be served from a subpath
	# of your site, rather than the site root:
	#    path("pages/", include(wagtail_urls)),
)

winwheel/urls.py
from . import views
from django.urls import path
urlpatterns = [
    path('', views.winwheel, name='winwheel'),
    path('js', views.winwheel_js, name='winwheel_js'),
    path('parameters', views.parameters, name='parameters'),
    path('sections', views.sections, name='sections'),
    path('spin', views.spin, name='spin'),
]

newsletter/models.py
from django.conf import settings
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.db import models
from django.utils.translation import gettext_lazy as _

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.images.models import Image as WagtailImage

from modelcluster.models import ClusterableModel

from webshop.utils import encode, decode

SECRET_KEY = 'ABCDABCDABCDABCDABCDABCDABCD'


class NewsletterCampaign(ClusterableModel):
	title = models.TextField()
	image = models.ForeignKey(
		WagtailImage,
		null=True,
		blank=True,
		on_delete=models.SET_NULL,
		related_name='+'
	)
	text = models.TextField()
	title_done = models.TextField(help_text=_('Title for the popup after subscribing'))
	text_done = models.TextField(help_text=_('Text for the popup after subscribing'))
	active = models.BooleanField(default=True)

	panels = [
		FieldPanel('title'),
		ImageChooserPanel('image'),
		FieldPanel('text'),
		FieldPanel('title_done'),
		FieldPanel('text_done'),
		FieldPanel('active'),
	]

	class Meta:
		verbose_name = _('Newsletter campaign')
		verbose_name_plural = _('Newsletter campaigns')

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		for lan in settings.LANGUAGES:
			key = make_template_fragment_key('newsletter_popup_js', [lan[0]])
			cache.delete(key)
		key = make_template_fragment_key('newsletter_popup_js')
		cache.delete(key)
		return super().save(*args, **kwargs)


class Subscriber(ClusterableModel):
	email = models.EmailField(unique=True)
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = _('Subscriber')
		verbose_name_plural = _('Subscribers')
		ordering = ('created', 'email')

	def __str__(self):
		return self.email

	@property
	def encoded_email(self):
		return encode(SECRET_KEY, self.email)

	@staticmethod
	def decode_email(encoded_mail):
		return decode(SECRET_KEY, encoded_mail)

	@staticmethod
	def is_encoded_email_valid(encoded_email):
		"""
		If encoded email is valid
		"""
		subscriber = Subscriber.objects.filter(email=decode(SECRET_KEY, encoded_email))
		return len(subscriber) != 0

newsletter/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from newsletter.models import Subscriber


class SubscribeForm(forms.ModelForm):
	email = forms.CharField(
		label=_('Email'), 
		widget=forms.TextInput(
			attrs={
				'type': 'text',
				'placeholder': 'email@gmail.com'
			}
		)
	)

	class Meta:
		model = Subscriber
		fields = ('email', )

newsletter/views.py
import json

from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from newsletter.forms import SubscribeForm
from newsletter.models import NewsletterCampaign, Subscriber

from webshop.utils import get_errors_from_form


def newsletter_base(request):
	"""
	Newsletter base view. E.g. footer
	"""
	errors = ""
	subscriber_form = SubscribeForm()
	if request.method == 'POST':
		subscriber_form = SubscribeForm(request.POST)
		if subscriber_form.is_valid():
			subscriber_form.save()
		else:
			errors = get_errors_from_form(subscriber_form)
	return render(request, 'newsletter/footer.html', {'subscriber_form': subscriber_form, 'errors': errors})


def unsubscribe_view(request, encoded_email):
	"""
	Unsubscribe from newsletter view
	"""
	subscriber = get_object_or_404(Subscriber, email=Subscriber.decode_email(encoded_email))
	subscriber.delete()
	return render(request, 'newsletter/unsubscribe.html', {'email': subscriber.email})


def subscribe(request):
	"""
		returns {
			'success': true,
		}
		returns {
			'exception': 'You are already subscribed',
		}
	"""
	body_unicode = request.body.decode('utf-8')
	data = json.loads(body_unicode)
	subscriber_form = SubscribeForm(data)
	if subscriber_form.is_valid():
		subscriber_form.save()
		return JsonResponse({
			'success': True,
		})
	else:
		return JsonResponse({
			'exception': get_errors_from_form(subscriber_form)
		})


def popup(request):
	subscriber_form = SubscribeForm()
	x = NewsletterCampaign.objects.filter(active=True)[0]
	return render(request, 'newsletter/popup.html', {
		'newsletter_campaign': x,
		'form': subscriber_form,
	})


def popup_js(request):
	return render(request, 'newsletter/popup_js.html')

newsletter/templates/newsletter/footer.html
{% load i18n %}
{% block base_newsletter %}
<div id="footer-newsletter" class="text-align-center">
  <h2 id="footer-newsletter-title">{% trans 'Abboniere unseren Newsletter' %}</h2>
  {% if not errors %}
    <div>{% trans 'Abonniert' %}</div>
    {% endif %}
  {% if errors %}
    <div>{{ errors }}</div>
  {% endif %}
  <form id="footer-newsletter-form" action="{% url 'newsletter:newsletter_base' %}" class="m-auto">
    <div class="m-auto d-flex">
      <input class="form-input" type="text" required id="{{ subscriber_form.email.id_for_label }}"
        name="{{ subscriber_form.email.html_name }}" placeholder="email@gmail.com" />
      {% csrf_token %}
      <button class="custom-button-light" type="submit" name="subscribe">
        {% trans 'Abonnieren' %}
      </button>
    </div>
  </form>
</div>
<script>
  $('#footer-newsletter-form').submit(function (e) {
    e.preventDefault();
    $.post("{% url 'newsletter:newsletter_base' %}", $(this).serialize(), function (data) {
      $('#footer-newsletter').replaceWith(data);
    });
  });
</script>
{% endblock %}

newsletter/templates/newsletter/popup.html
{% load i18n static %}
<div class="w-full">
	<div class="absolute top-4 right-4 text-xl text-gray-400 pl-3 pb-3 cursor-pointer"
	onclick="hideNewsletterPopup();">
		<i class="fal fa-times hoverable-gray-black pl-4 pb-4"></i>
	</div>
	<div class="flex lg:items-center sm:max-w-md ">
		<div id="newsletterPopUpDone" class="flex flex-col w-full hidden">
			<h2 class="text-center font-bold mb-4">
				{{ newsletter_campaign.title_done }}
			</h2>
			<div class="mb-4">
				{{ newsletter_campaign.text_done }}
			</div>
			<button type="button"
					class="button-secondary-outline block w-full rounded p-3 text-lg text-center" 
					onclick="hideNewsletterPopup();">
				{% trans 'Close' %}
			</button>
		</div>
		<div id="newsletterPopUpForm" class="flex flex-col w-full">
			<h2 class="text-center font-bold mb-4">
				{{ newsletter_campaign.title }}
			</h2>
			<div>
				<form action="{% url 'winwheel:spin' %}" onsubmit='event.preventDefault(); subscribeToNewsletterPopUp(this);'>
					{% if newsletter_campaign.image %}
						<img src="{{ newsletter_campaign.image.url }}" alt="{{ newsletter_campaign.image.file.name }}" 
							class="w-full mb-4"/>
					{% endif %}
					<div class="text-left mb-4">
						{{ newsletter_campaign.text }}
					</div>
					<div id="newsletterPopUpError" 
							class="p-3 mb-2 border border-red-400 bg-red-200 rounded text-left text-sm text-red-800 hidden">
					</div>
					<div class="form-label-group mb-4">
						<input type="email" name="{{ form.email.html_name }}" id="{{ form.email.id_for_label }}"
							placeholder="{{ form.email.field.widget.attrs.placeholder }}" required="true" />
						<label for="{{ form.email.id_for_label }}">
							{{ form.email.label }}
						</label>
					</div>
					{% csrf_token %}
					<button class="button-primary-outline block w-full rounded p-3 text-lg text-center">
						{% trans 'Subscribe' %}
					</button>
				</form>
			</div>
		</div>
	</div>
</div>

newsletter/templates/newsletter/popup_js.html
{% load static i18n %}
<html>
	<head></head>
	<body>
		<script>			
			async function subscribeToNewsletterPopUp(form){
				const formData = new FormData(form);
				let data = {};
				for (let [key, value] of formData.entries()) {
					data[key] = value;
				}
				let response = await fetch('{% url "newsletter:subscribe" %}', {
					method: 'POST',
					mode: 'cors',
					cache: 'default',
					headers: {
						'Accept': 'application/json',
						'Content-Type': 'application/json',
						'X-CSRFToken': getCookie('csrftoken')
					},
					body: JSON.stringify(data),
				});
				response = await response.json();
				const newsletterError = document.getElementById('newsletterPopUpError');
				const newsletterDone = document.getElementById('newsletterPopUpDone');
				const newsletterForm = document.getElementById('newsletterPopUpForm');
				if(response['exception'] !== undefined){
					newsletterError.classList.remove('hidden');
					newsletterError.innerText = response['exception'];
				} else{
					newsletterForm.classList.add('hidden');
					newsletterDone.classList.remove('hidden');
				}
			}
		</script>
	</body>
</html>

newsletter/templates/newsletter/unsubscribe.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Login" %}{% endblock %}

{% block content %}

<div class="flex flex-col items-center text-center p-2 sm:p-4">
	<h1 class="my-16">
		{% trans 'Unsubscribed' %}
	</h1>
	<div class="w-full max-w-lg my-auto mb-16">
		{% trans 'You have unsubscribed from our newsletter' %} {{ email }}
	</div>
</div>
{% endblock %}