blog/urls.py
from django.urls import path

from blog import views


urlpatterns = [
	path('tagify_query/', views.tagify_query, name='tagify_query'),
]

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.details, name='details'),
	path('add/<int:product_color_quantity_id>/<int:quantity>', views.add, name='add'),
	path('update/<int:product_color_quantity_id>/<int:quantity>', views.update, name='update'),
	path('cart_overlay_content', views.cart_overlay_content, name='cart_overlay_content'),
	path('cart_checkout_top', views.cart_checkout_top, name='cart_checkout_top'),
	path('cart_checkout_right', views.cart_checkout_right, name='cart_checkout_right'),
]

webshop/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from home.views import home
from search import views as search_views

urlpatterns = i18n_patterns(
	path('', home, name=''),
	path('i18n/', include('django.conf.urls.i18n')),
	path('django-admin/', admin.site.urls),
	path('admin/', include(wagtailadmin_urls)),
	path('documents/', include(wagtaildocs_urls)),
	path('search/', search_views.search, name='search'),
	path('password-reset/complete/', 
		auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
		name='password_reset_complete'),
	path(_('home/'), include(('home.urls', 'home'), namespace='home')),
	path(_('account/'), include(('account.urls', 'account'), namespace='account')),
	path(_('blog/'), include(('blog.urls', 'blog'), namespace='blog')),
	path(_('cart/'), include(('cart.urls', 'cart'), namespace='cart')),
	path(_('contact/'), include(('contact.urls', 'contact'), namespace='contact')),
	path(_('coupon/'), include(('coupon.urls', 'coupon'), namespace='coupon')),
	path(_('newsletter/'), include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
	path(_('order/'), include(('order.urls', 'order'), namespace='order')),
	path(_('shop/'), include(('shop.urls', 'shop'), namespace='shop')),
	path(_('winwheel/'), include(('winwheel.urls', 'winwheel'), namespace='winwheel')),
	path('rosetta/', include('rosetta.urls')),
)



if settings.DEBUG:
	import debug_toolbar
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns = urlpatterns + i18n_patterns(
	# For anything not caught by a more specific rule above, hand over to
	# Wagtail's page serving mechanism. This should be the last pattern in
	# the list:
	path('', include(wagtail_urls)),

	# Alternatively, if you want Wagtail pages to be served from a subpath
	# of your site, rather than the site root:
	#    path("pages/", include(wagtail_urls)),
)

cart/models.py
import logging
from django.db import models
from django.db.utils import ProgrammingError
from django.utils.translation import gettext_lazy as _


logger = logging.getLogger('django')
maximum_order_quantity: int = None
save_abandoned_cart: int = None


class Setting(models.Model):
	key = models.CharField(max_length=255, db_index=True, unique=True)
	value = models.CharField(max_length=255, db_index=True)

	class Meta:
		verbose_name = 'Setting'
		verbose_name_plural = 'Settings'
		ordering = ['key']

	def __str__(self):
		return self.key

	@staticmethod
	def get_MAXIMUM_ORDER_QUANTITY() -> int:
		"""
		Get the maximum order quantity
		"""
		global maximum_order_quantity
		if maximum_order_quantity is None:
			try:
				maximum_order_quantity = int(Setting.objects.get(key='MAXIMUM_ORDER_QUANTITY').value)
			except ProgrammingError:
				logging.error(_('Run python manage.py migrate'))
				return True
			except Setting.DoesNotExist:
				return 20
			except Exception as e:
				logging.error(str(e))
				return 20
		return maximum_order_quantity

	@staticmethod
	def get_SAVE_ABANDONED_CART() -> bool:
		"""
		Get the maximum order quantity
		"""
		global save_abandoned_cart
		if save_abandoned_cart is None:
			try:
				save_abandoned_cart = Setting.objects.get(key='SAVE_ABANDONED_CART').value.lower() == 'yes'
			except ProgrammingError:
				logging.error(_('Run python manage.py migrate'))
				return True
			except Setting.DoesNotExist:
				return True
			except Exception as e:
				logging.error(str(e))
				return True
		return save_abandoned_cart

	def save(self, *args, **kwargs) -> None:
		super().save(*args, **kwargs)
		if self.key == 'MAXIMUM_ORDER_QUANTITY':
			global maximum_order_quantity
			maximum_order_quantity = self.value
		elif self.key == 'SAVE_ABANDONED_CART':
			global save_abandoned_cart
			save_abandoned_cart = self.value

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from shop.models import ProductColorQuantity


class AddProductToCartForm(forms.Form):
	size = forms.ModelChoiceField(
		queryset=ProductColorQuantity.objects.all(),
	)
	quantity = forms.CharField()
	update = forms.BooleanField(
		required=False,
		initial=False,
		widget=forms.HiddenInput
	)

	def __init__(self, product_color_id, *args, **kwargs):
		super(AddProductToCartForm, self).__init__(*args, **kwargs)
		product_quantities = ProductColorQuantity.objects.get(product_color_id).excluse(quantity=0)
		self.fields['size'] = forms.ModelChoiceField(
			queryset=product_quantities,
			widget=forms.Select,
			empty_label=_('Sold out') if not product_quantities else None
		)

	def clean_quantity(self):
		quantity = self.cleaned_data.get('quantity')
		if quantity.isdigit() and int(quantity) > 0:
			return quantity
		raise forms.ValidationError(_('Enter a positive quantity'))


class ChangeProductQuantityForm(forms.Form):
	quantity = forms.CharField()
	update = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

	def clean_quantity(self):
		quantity = self.cleaned_data.get('quantity')
		if quantity.isdigit() and int(quantity) > 0:
			return quantity
		raise forms.ValidationError(_('Enter a positive quantity'))

cart/views.py
import json
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from cart.cart import Cart

from shop.models import ProductListingsPage, ProductColorQuantity


def add(request, product_color_quantity_id: str, quantity: str):
	"""
	Add product to cart
	"""
	cart = Cart(request)
	try:
		quantity = int(quantity)
		if quantity < 1:
			return JsonResponse({
				'data': {
					'success': False,
					'message': {
						'title': str(_('Error while adding to cart')),
						'innerHtml': str(_('Please enter a number greater than 0')),
						'tag': 'error'
					}
				}
			})
		product_color_quantity = ProductColorQuantity.objects.get(id=product_color_quantity_id)
		return JsonResponse(cart.add(
			product_color_quantity=product_color_quantity,
			quantity=quantity,
			update_quantity=False
		))
	except ProductColorQuantity.DoesNotExist:
		return JsonResponse({
			'data': {
				'success': False,
				'message': {
					'title': str(_('Error while adding to cart')),
					'innerHtml': str(_('There is no product with the id %(product_color_quantity_id)') %
							{'product_color_quantity_id': product_color_quantity_id}),
					'tag': 'error'
				}
			}
		})
	except ValueError:
		return JsonResponse({
			'data': {
				'success': False,
				'message': {
					'title': str(_('Error while adding to cart')),
					'innerHtml': str(_('Please enter a valid number')),
					'tag': 'error'
				}
			}
		})
	except Exception as ex:
		return JsonResponse({
			'data': {
				'success': False,
				'message': {
					'title': str(_('Error while adding to cart')),
					'innerHtml': str(ex),
					'tag': 'error'
				}
			}
		})


def update(request, product_color_quantity_id: str, quantity: str):
	"""
	Update quantity of a ProductColorQuantity in cart
	"""
	cart = Cart(request)
	try:
		quantity = int(quantity)
		if quantity < 0:
			return JsonResponse({
				'data': {
					'success': False,
					'message': {
						'title': str(_('Error while updating cart')),
						'innerHtml': str(_('Please enter a number greater than 0')),
						'tag': 'error'
					}
				}
			})
		product_color_quantity = ProductColorQuantity.objects.get(id=product_color_quantity_id)
		return JsonResponse(cart.add(
			product_color_quantity=product_color_quantity,
			quantity=quantity,
			update_quantity=True
		))
	except ProductColorQuantity.DoesNotExist:
		return JsonResponse({
			'data': {
				'success': False,
				'message': {
					'title': str(_('Error while updating cart')),
					'innerHtml': str(_('There is no product with the id %(product_color_quantity_id)') %
							{'product_color_quantity_id': product_color_quantity_id}),
					'tag': 'error'
				}
			}
		})
	except ValueError:
		return JsonResponse({
			'data': {
				'success': False,
				'message': {
					'title': str(_('Error while updating cart')),
					'innerHtml': str(_('Please enter a valid number')),
					'tag': 'error'
				}
			}
		})
	except Exception as ex:
		return JsonResponse({
			'data': {
				'success': False,
				'message': {
					'title': str(_('Error while updating cart')),
					'innerHtml': str(ex),
					'tag': 'error'
				}
			}
		})


def cart_overlay_content(request):
	cart = Cart(request)
	return render(request, 'cart/cart_overlay.html', {
		'cart': cart,
		'products_url': ProductListingsPage.objects.all()[0].link
	})


def cart_checkout_top(request):
	cart = Cart(request)
	return render(request, 'cart/cart_checkout_top.html', {
		'cart': cart,
	})


def cart_checkout_right(request):
	cart = Cart(request)
	return render(request, 'cart/cart_checkout_right.html', {
		'cart': cart,
	})


def details(request):
	cart = Cart(request)
	available = {}
	out_of_stock = []
	if not cart.is_good and len(cart) != 0:
		cart.calc_overflow()
		available = cart.cart['available']
		out_of_stock = cart.cart['out_of_stock']
		messages.error(
			request, 
			json.dumps({
				'data': {
					'title': str(_('Update cart')),
					'innerHTML': str(_('There is not enough stock available for your order, please update your cart.')),
					'type': 'error'
				}
			})
		)
	return render(request, 'cart/details.html', {
		'cart': cart,
		'available': available,
		'available_keys': list(available.keys()),
		'out_of_stock': out_of_stock,
		'products_url': ProductListingsPage.objects.all()[0].link,
	})

cart/templates/cart/cart_overlay.html
{% load i18n static cart_template_tags shop_template_tags %}
{% get_currency as currency %}
{% with total_items=cart|length %}

{% if total_items != 0 %}
	<div class="flex flex-col h-screen py-4">
		<div class="flex flex-grow-0 justify-between px-2 sm:px-4">
			<h3 class="mb-0">{% trans 'Your cart' %}</h1>
			<div class="flex self-center">
				<span class="cursor-pointer" onclick="hideCart();">
					<i class="fal fa-times hoverable-gray-black text-2xl pl-4 pb-4"></i>
				</span>
			</div>
		</div>
		<div class="flex-grow overflow-y-auto px-2 sm:px-4">
			{% for item in cart %}
				{% get_product_color item.product_color_id as product_color %}
				{% get_product_size item.product_size_id as product_size %}
				{% get_product_color_quantity item.product_color_quantity_id as product_color_quantity %}
				<div class="flex items-center py-4 border-t border-gray-200">
					<a href="{{ product_color.product.link }}" aria-label="{% trans 'Product' %}" class="cursor-pointer mr-4">
						<div class="flex items-center justify-center w-20">
							<div class="aspect-1-1 bg-center bg-cover rounded border border-gray-200"
								style="background-image: url('{{ product_color.image.file.url }}');">
							</div>
						</div>
					</a>
					<form class="w-full"
						onsubmit="event.preventDefault(); updateOverlayQuantity(this, '{{ product_color_quantity.id }}');">
						<div class="flex justify-between w-full relative">
							<div class="flex flex-col">
								<h4 class="text-lg cursor-text mb-0" style="line-height: 1.2;">{{ product_color.product.title }}</h4>
								<p class="text-xs cursor-text mb-0">{{ product_color_quantity.get_display_variation }}</p>
								<p class="text-xs cursor-text mb-0">{{ product_color.product.get_display_price }}</p>
								<div>
									<div class="flex">
										<input class="block w-16 h-8 p-1 text-sm rounded-l border border-gray-400 
												focus:border-black" aria-label="{% trans 'Quantity' %}"
												name="quantity" type="number" min="1" value="{{ item.quantity }}"/>
										<button name="updateQuantity" class="block rounded-r h-8 w-8 button-primary"
												aria-label="{% trans 'Update quantity' %}">
											<i class="fal fa-sync"></i>
										</button>
									</div>
								</div>
								<div class="absolute bottom-0 right-0 text-sm cursor-text">
									{% get_display_currency_price item.total_price %}
								</div>
							</div>
							<div class="flex items-center hoverable-gray-black pl-4"
								onclick="updateOverlayQuantity(this.parentElement.parentElement, '{{ product_color_quantity.id }}', 0);">
								<i class="fal fa-times padding-4"></i>
							</div>
						</div>
					</form>
				</div>
			{% endfor %}
		</div>
		<div class="flex flex-grow-0 flex-col px-2 sm:px-4">
			<div class="py-4 border-t border-b border-gray-200">
				<div class="w-full">
					<form action="POST" class="couponForm"
						onsubmit="event.preventDefault(); applyCoupon(this);">
						<div class="flex flex-col">
							<div class="coupon-error p-3 mb-4 border border-red-400 bg-red-200 rounded text-red-800 hidden">
								{% trans 'The code you entered seems to be invalid' %}
							</div>
							<div class="flex">
								{% csrf_token %}
								<input class="block w-full h-12 p-1 rounded-l border border-gray-300 focus:border-black" 
									name="coupon" placeholder="{% trans 'Coupon' %}" required/>
								<button class="button-primary rounded-r h-12 w-20">
									{% trans 'Apply' %}
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="py-4 flex border-b border-gray-200 justify-between">
				<div>
					{% trans 'Subtotal' %}
				</div>
				<div>
					{{ cart.get_display_pre_coupon_price }}
				</div>
			</div>
			{% if cart.coupon %}
				<div class="mt-4 pb-4 flex border-b border-gray-200 justify-between coupon-class">
					<div class="flex align-center items-center">
						{% if cart.coupon.coupon_type == 'Credit' %}
							{{ cart.coupon.code }} ({{ cart.coupon.display_credit_value }})
						{% else %}
							{{ cart.coupon.code }} ({{ cart.coupon.display_percentage }})
						{% endif %}
						<div onclick="removeCoupon();" class="ml-2 cursor-pointer flex align-center items-center">
							<i class="fal fa-times hoverable-gray-black transition-all text-lg"></i>
						</div>
					</div>
					<div>
						- {{ cart.get_display_discount }}
					</div>
				</div>
			{% endif %}
			<div class="mt-4 flex justify-between pb-4 border-b border-gray-200">
				<h5 class="text-xl">{% trans 'Total' %}</h5>
				<h5 class="text-xl">{{ cart.get_display_price_pre_shipping }}</h5>
			</div>
			<div class="flex flex-col sm:flex-row mt-4">
				<a href="{% url 'cart:details' %}"
					class="button-secondary-outline	w-full rounded p-3 text-lg text-center sm:mr-1 mb-4 sm:mb-0">
					{% trans 'Cart' %}
				</a>
				<a href="{% url 'order:information' %}"
					class="button-primary-outline w-full rounded p-3 text-lg text-center sm:ml-1">
					{% trans 'Checkout' %}
				</a>
			</div>
		</div>
	</div>
{% else %}
	<div class="flex flex-col h-screen py-4 px-2 sm:px-4 ">
		<div class="flex flex-grow-0 justify-between px-2 sm:px-4">
			<h3 class="mb-0">{% trans 'Your cart' %}</h1>
			<div class="flex self-center">
				<span class="cursor-pointer" onclick="hideCart();">
					<i class="fal fa-times hoverable-gray-black text-2xl pl-4 pb-4"></i>
				</span>
			</div>
		</div>
		<div class="flex flex-col flex-grow justify-center text-center w-full">
			<i class="fal fa-shopping-cart text-8xl mb-4"></i>
			<h3 class="mb-4">{% trans 'Your cart is empty' %}</h3>
			<p class="mb-8">{% trans 'It seems like you have not added any items to your cart' %}</p>
			<div>
				<a class="block button-primary-outline w-full transition-all rounded p-3 text-lg text-center sm:mr-1 mb-4 
						sm:mb-0" href="{{ products_url }}">
					{% trans 'View Shop' %}
				</a>
			</div>
		</div>
	</div>
{% endif %}

{% endwith %}

cart/templates/cart/details.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load wagtailcore_tags wagtailimages_tags wagtailroutablepage_tags %}
{% load i18n cart_template_tags shop_template_tags %}

{% block title %}
	{% trans 'Cart' %}
{% endblock %}
{% block content %}
	{% get_currency as currency %}
	<div class="m-auto p-2 sm:p-4 max-w-xl">
		<div class="mt-8 mb-8 text-center ">
			<h1 class="mb-0">{% trans 'Your cart' %}</h1>
		</div>
		<div id="cartDetailsDiv">
			<div class="w-full">
				{% with total_items=cart|length %}
				{% if total_items != 0 %}
					<div>
						{% for item in cart %}
							{% get_product_color item.product_color_id as product_color %}
							{% get_product_size item.product_size_id as product_size %}
							{% get_product_color_quantity item.product_color_quantity_id as product_color_quantity %}
							<div class="flex items-center mt-4 pb-4 border-b border-gray-200">
								<a href="{{ product_color.product.link }}" aria-label="{% trans 'Product' %}" 
										class="cursor-pointer mr-4">
									<div class="flex items-center justify-center w-20">
										<div class="aspect-1-1 bg-center bg-cover rounded border border-gray-200"
											style="background-image: url('{{ product_color.image.file.url }}');">
										</div>
									</div>
								</a>
								<form class="w-full" 
										onsubmit="event.preventDefault(); updateQuantity(this, '{{ product_color_quantity.id }}');">
									<div class="flex justify-between w-full relative">
										<div class="flex flex-col">
											<h4 class="text-lg" style="line-height: 1.2;">
												{% if item.product_color_quantity_id in out_of_stock %}
													<s>{{ product_color.product.title }}</s>
												{% else %}
													{{ product_color.product.title }}
												{% endif %}
											</h4>
											<h6 class="text-xs">{{ product_color_quantity.get_display_variation }}</h6>
											<h6 class="text-xs">{{ product_color.product.get_display_price }}</h6>
											<div>
												<div class="flex">
													<input class="block w-16 h-8 p-1 text-sm rounded-l border border-gray-400 
															focus:border-black" aria-label="{% trans 'Quantity' %}"
															name="quantity" type="number" min="1" value="{{ item.quantity }}"/>
													<button class="button-primary rounded-r h-8 w-8"
															aria-label="{% trans 'Update quantity' %}">
														<i class="fal fa-sync"></i>
													</button>
													<div class="flex items-center text-red-500 text-sm ml-1">
														{% if item.product_color_quantity_id in available_keys %}
															{% blocktrans with stock=available|get_item:item.product_color_quantity_id %}
																(Only {{ stock }} left)
															{% endblocktrans %}
														{% endif %}
														{% if item.product_color_quantity_id in out_of_stock %}
															({% trans 'Out of stock' %})
														{% endif %}
													</div>
												</div>
											</div>
											<div class="absolute bottom-0 right-0 text-sm cursor-text">
												{% get_display_currency_price item.total_price %}
											</div>
										</div>
										<div class="flex items-center hoverable-gray-black pl-4"
											onclick="updateQuantity(this.parentElement.parentElement, '{{ product_color_quantity.id }}', 0);"
												aria-label="{% trans 'Update quantity' %}">
												<i class="fal fa-times padding-4"></i>
										</div>
									</div>
								</form>
							</div>
						{% endfor %}
					</div>
					<div class="mt-4 pb-4 border-b border-gray-200">
						<div class="w-full">
							<form action="POST" class="coupon-form"
								onsubmit="event.preventDefault(); applyCoupon(this, true);">
								<div class="flex flex-col">
									<div class="coupon-error p-3 mb-4 border border-red-400 bg-red-200 rounded text-red-800 hidden">
										{% trans 'The code you entered seems to be invalid' %}
									</div>
									<div class="flex">
										{% csrf_token %}
										<input class="block w-full h-12 p-1 rounded-l border border-gray-300 focus:border-black" 
											name="coupon" placeholder="{% trans 'Coupon' %}" required/>
										<button class="button-primary rounded-r h-12 w-20 transition-all text-white">
											{% trans 'Apply' %}
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
					<div class="py-4 flex border-b border-gray-200 justify-between">
						<div>
							{% trans 'Subtotal' %}
						</div>
						<div>
							{{ cart.get_display_pre_coupon_price }}
						</div>
					</div>
					{% if cart.coupon %}
						<div class="mt-4 pb-4 flex border-b border-gray-200 justify-between coupon-class">
							<div class="flex align-center items-center">
								{% if cart.coupon.coupon_type == 'Credit' %}
									{{ cart.coupon.code }} ({{ cart.coupon.display_credit_value }})
								{% else %}
									{{ cart.coupon.code }} ({{ cart.coupon.display_percentage }})
								{% endif %}
								<div onclick="removeCoupon(true);" class="ml-2 cursor-pointer flex align-center items-center">
									<i class="fal fa-times hoverable-gray-black text-lg"></i>
								</div>
							</div>
							<div>
								- {{ cart.get_display_discount }}
							</div>
						</div>
					{% endif %}
					<div class="mt-4 flex justify-between pb-4 border-b border-gray-200">
						<h5 class="text-xl">{% trans 'Total' %}</h5>
						<h5 class="text-xl">{{ cart.get_display_price_pre_shipping }}</h5>
					</div>
					<div class="flex flex-col sm:flex-row mt-4">
						<a href="{% url 'order:information' %}"
							class="block w-full transition-all rounded p-3 text-lg text-center button-primary-outline">
							{% trans 'Checkout' %}
						</a>
					</div>
				{% else %}
					<div class="cart-empty-container text-center flex flex-col justify-center" style="min-height: 60vh;">
						<div class="w-100">
							<i class="fal fa-shopping-cart text-8xl mb-4"></i>
							<h3 class="mb-4 text-2xl">{% trans 'Your cart is empty' %}</h4>
							<p class="mb-8">{% trans 'It seems like you have not added any items to your cart' %}</p>
							<div>
								<a class="block button-primary-outline w-full transition-all rounded p-3 text-lg text-center sm:mr-1 
										mb-4 sm:mb-0" href="{{ products_url }}">
									{% trans 'View Shop' %}
								</a>
							</div>
						</div>
					</div>
				{% endif %}
				{% endwith %}
			</div>
		</div>
	</div>
{% endblock %}