blog/urls.py
from django.urls import path

from blog import views


urlpatterns = [
	path('tagify_query/', views.tagify_query, name='tagify_query'),
]

order/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.information, name='information'),
	path('shipping', views.shipping, name='shipping'),
	path('payment', views.payment, name='payment'),
	path('view/<order_url>', views.view, name='view'),
	path('paypal-webhook/', views.paypal_webhook, name='paypal_webhook'),
	path('paypal-verification/<paypal_order_id>', views.paypal_verification, name='paypal_verification'),
	path('stripe-verification/<payment_intent_id>', views.stripe_verification, name='stripe_verification'),
	path('stripe-webhook/', views.stripe_webhook, name='stripe_webhook'),
	path('admin-order-detail/<order_id>', views.admin_order_detail, name='admin_order_detail'),
	path('invoice-pdf/<order_id>', views.invoice_pdf, name='invoice_pdf'),
	#path('confirmation-email/<order_id>', views.confirmation_email, name='confirmation_email'),
	#path('shipping-email/<order_id>', views.shipping_email, name='shipping_email'),
]

webshop/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from home.views import home
from search import views as search_views

urlpatterns = i18n_patterns(
	path('', home, name=''),
	path('i18n/', include('django.conf.urls.i18n')),
	path('django-admin/', admin.site.urls),
	path('admin/', include(wagtailadmin_urls)),
	path('documents/', include(wagtaildocs_urls)),
	path('search/', search_views.search, name='search'),
	path('password-reset/complete/', 
		auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
		name='password_reset_complete'),
	path(_('home/'), include(('home.urls', 'home'), namespace='home')),
	path(_('account/'), include(('account.urls', 'account'), namespace='account')),
	path(_('blog/'), include(('blog.urls', 'blog'), namespace='blog')),
	path(_('cart/'), include(('cart.urls', 'cart'), namespace='cart')),
	path(_('contact/'), include(('contact.urls', 'contact'), namespace='contact')),
	path(_('coupon/'), include(('coupon.urls', 'coupon'), namespace='coupon')),
	path(_('newsletter/'), include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
	path(_('order/'), include(('order.urls', 'order'), namespace='order')),
	path(_('shop/'), include(('shop.urls', 'shop'), namespace='shop')),
	path(_('winwheel/'), include(('winwheel.urls', 'winwheel'), namespace='winwheel')),
	path('rosetta/', include('rosetta.urls')),
)



if settings.DEBUG:
	import debug_toolbar
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns = urlpatterns + i18n_patterns(
	# For anything not caught by a more specific rule above, hand over to
	# Wagtail's page serving mechanism. This should be the last pattern in
	# the list:
	path('', include(wagtail_urls)),

	# Alternatively, if you want Wagtail pages to be served from a subpath
	# of your site, rather than the site root:
	#    path("pages/", include(wagtail_urls)),
)

order/views.py
import json
import logging
import stripe

from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import translation
from django.views.decorators.csrf import csrf_exempt

from account.utils import get_user_from_request
from cart.cart import Cart
from order.forms import AddressForm, OrderCreateForm, ShippingForm
from order.models import Order, OrderItem, OrderStatus, ShippingMethod, State, Setting
from order.order import Order as OrderSession
from order.paypal import PayPalClient
from order.utils import get_invoice, reduce_coupon, reduce_stock
from order.tasks import check_if_order_paid, save_invoice, send_invoice
from shop.models import ProductColorQuantity, Setting as ShopSetting


logger = logging.getLogger('django')
paypal_client = PayPalClient()
stripe.api_key = Setting.get_STRIPE_SECRET_KEY()


def information(request):
	"""
	Set customer information for order view
	"""
	user = get_user_from_request(request)
	cart = Cart(request)
	order = OrderSession(request)
	initial_data = {}
	if user:
		if user.address.all():
			address = user.address.all()[0]
			initial_data = {
				'email': address.email, 
				'first_name': address.first_name, 
				'last_name': address.last_name, 
				'company': address.company, 
				'address': address.address, 
				'address2': address.address2,  
				'city': address.city,  
				'country': address.country,  
				'state': address.state,  
				'postal_code': address.postal_code, 
				'telephone': address.telephone,
			}
			order.set_address(initial_data)
	form = OrderCreateForm(initial=initial_data)
	if cart.is_good:
		if request.method == 'POST':
			form = OrderCreateForm(request.POST)
			if form.is_valid():
				order.set_address(form.cleaned_data)
				if user:
					updated_request = request.POST.copy()
					updated_request.update({'user': user.id})
					address = AddressForm(user.id, updated_request)
					if address.is_valid():
						address.save()
						if not user.first_name:
							user.first_name = address.cleaned_data['first_name']
							user.last_name = address.cleaned_data['last_name']
							user.save()
						pass
				request.session['shipping'] = True
				return redirect(reverse('order:shipping'))
	else:
		return redirect(reverse('cart:details'))
	return render(request, 'order/information.html', {
		'cart': cart,
		'form': form,
		'order': order,
		'states': json.dumps(State.get_dict())
	})


def shipping(request):
	"""
	Set customer information for order view
	"""
	cart = Cart(request)
	order = OrderSession(request)
	if not request.session.get('shipping'):
		return redirect(reverse('order:information'))
	if not cart.is_good:
		return redirect(reverse('cart:details'))
	if request.method == 'POST':
		shipping_form = ShippingForm(cart.get_total_weight(), request.POST)
		if shipping_form.is_valid():
			cart.set_shipping_id(shipping_form.cleaned_data['method'].id)
			return redirect(reverse('order:payment'))
		else:
			return render(request, 'order/shipping.html', {
				'cart': cart,
				'order': order.order,
				'form': shipping_form
			})
	return render(request, 'order/shipping.html', {
		'cart': cart,
		'order': order.order,
		'form': ShippingForm(cart.get_total_weight())
	})


def payment(request):
	cart = Cart(request)
	order_session = OrderSession(request)
	shipping_method = cart.shipping_method
	if not shipping_method:
		return redirect(reverse('order:shipping'))
	if not cart.is_good:
		return redirect(reverse('cart:details'))
	user = get_user_from_request(request)
	order = None
	if cart.order and not cart.order.paid:
		order = cart.order
	else:
		coupon = cart.coupon
		order = Order.objects.create(
			user=user,
			url=Order.generate_random_string(),
			email=order_session.order['email'],
			first_name=order_session.order['first_name'],
			last_name=order_session.order['last_name'],
			company=order_session.order['company'],
			address=order_session.order['address'],
			address2=order_session.order['address2'],
			postal_code=order_session.order['postal_code'],
			country=order_session.order['country'],
			city=order_session.order['city'],
			state=order_session.order['state'],
			telephone=order_session.order['telephone'],
			comment=order_session.order['comment'],
			shipping_method=shipping_method,
			shipping_method_name=shipping_method.get_full_name(),
			shipping_method_price=shipping_method.get_price(),
			paid=False,
			coupon=coupon,
			coupon_name=coupon.get_full_name() if coupon else None,
			discount=cart.get_discount(),
		)
	order_items = []
	for item in cart:
		product_color_quantity = ProductColorQuantity.objects.get(id=item['product_color_quantity_id'])
		product_color = product_color_quantity.product_color
		order_items.append(
			OrderItem.objects.create(
				order=order,
				product_color_quantity=product_color_quantity,
				sku=product_color.id,
				name=product_color.product.title,
				price=product_color.product.get_price(),
				color=product_color.color,
				quantity=item['quantity'],
				size=product_color_quantity.product_size.name,
			)
		)
	stripe_payment_intent = create_stripe_payment_intent(order)
	paypal_order_id = paypal_client.create_order(order).result['id']
	reduce_stock(order)
	check_if_order_paid.apply_async(
		(order.id, stripe_payment_intent.id, paypal_order_id), 
		countdown=Setting.get_CHECKOUT_TIMEOUT())
	return render(request, 'order/payment.html', {
		'cart': cart,
		'order': order,
		'order_items': order_items,
		'shipping_method': shipping_method,
		'stripe_publishable_key': Setting.get_STRIPE_PUBLISHABLE_KEY(),
		'paypal_client_id': Setting.get_PAYPAL_CLIENT_ID(),
		'stripe_payment_intent_client_secret': stripe_payment_intent.client_secret,
		'paypal_order_id': paypal_order_id
	})


def create_stripe_payment_intent(order) -> stripe.PaymentIntent:
	try:
		set_stripe_api_key()
		return stripe.PaymentIntent.create(
			amount=order.get_total_price(),
			currency=ShopSetting.get_CURRENCY_CODE_STRIPE(),
			payment_method_types=['card', 'sofort'],
			payment_method_options={
				'sofort': {
					'preferred_language': translation.get_language(),
				},
			},
			metadata={
				'order_id': str(order.id),
			},
			shipping={
				'address': {
					'city': order.city,
					'country': order.country,
					'line1': order.address,
					'line2': order.address2,
					'postal_code': order.postal_code,
					'state': order.state
				},
				'name': order.first_name + ' ' + order.last_name,
				'phone': order.telephone,
				'carrier': '',
				'tracking_number': '',
			}
		)
	except Exception as e:
		logger.error(e)
		raise e


@csrf_exempt
def stripe_webhook(request):
	payload = request.body
	event = None
	try:
		set_stripe_api_key()
		event = stripe.Event.construct_from(
			json.loads(payload), stripe.api_key
		)
	except stripe.error.CardError as e:
		# Since it's a decline, stripe.error.CardError will be caught
		print('Status is: %s' % e.http_status)
		print('Code is: %s' % e.code)
		# param is '' in this case
		print('Param is: %s' % e.param)
		print('Message is: %s' % e.user_message)
	except stripe.error.RateLimitError as e:
		# Too many requests made to the API too quickly
		logger.error('Too many requests made to the API too quickly: ' + e)
		return HttpResponse(status=400)
	except stripe.error.InvalidRequestError as e:
		# Invalid parameters were supplied to Stripe's API
		logger.error("Invalid parameters were supplied to Stripe's API: " + e)
		return HttpResponse(status=400)
	except stripe.error.AuthenticationError as e:
		# Authentication with Stripe's API failed
		# (maybe you changed API keys recently)
		logger.error("Authentication with Stripe's API failed (maybe you changed API keys recently): " + e)
		return HttpResponse(status=400)
	except stripe.error.APIConnectionError as e:
		# Network communication with Stripe failed
		logger.error('Network communication with Stripe failed: ' + e)
		return HttpResponse(status=400)
	except stripe.error.StripeError as e:
		# Display a very generic error to the user, and maybe send
		# yourself an email
		logger.error('Display a very generic error to the user, and maybe send yourself an email: ' + e)
		return HttpResponse(status=400)
	except ValueError as e:
		# Invalid payload
		return HttpResponse(status=400)
	except Exception as e:
		# Something else happened, completely unrelated to Stripe
		logger.error('Error: ' + str(e))
		return HttpResponse(status=400)
	# Handle the event
	if event.type == 'payment_intent.succeeded':
		payment_intent = event.data.object
		order = Order.objects.get(id=payment_intent['metadata']['order_id'])
		if not order.paid:
			order_processed(order, stripe_payment_id=payment_intent.stripe_id)
	elif event.type == 'payment_method.attached':
		payment_method = event.data.object  # contains a stripe.PaymentMethod
		print('PaymentMethod was attached to a Customer!')
	# ... handle other event types
	else:
		print('Unhandled event type {}'.format(event.type))
	return HttpResponse(status=200)


def stripe_verification(request, payment_intent_id):
	payment_intent = None
	try:
		set_stripe_api_key()
		payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
	except stripe.error.CardError as e:
		# Since it's a decline, stripe.error.CardError will be caught
		print('Status is: %s' % e.http_status)
		print('Code is: %s' % e.code)
		# param is '' in this case
		print('Param is: %s' % e.param)
		print('Message is: %s' % e.user_message)
	except stripe.error.RateLimitError as e:
		# Too many requests made to the API too quickly

order/templates/order/payment.html
{% extends 'base.html' %}
{% load static shop_template_tags cart_template_tags i18n %}
{% block overlay %}
	<div id="paymentOverlay" 
		class="z-40 fixed top-0 left-0 h-full w-full flex justify-center items-center text-white text-center
		overflow-y-auto bg-black bg-opacity-80 transition-opacity duration-500 z-40 hidden">
		<div class="absolute top-4 right-4 p-4 cursor-pointer" onclick="hidePaymentOverlay();">
			<i class="fal fa-times text-2xl"></i>
		</div>
		<div class="p-4">
			<i class="fal fa-circle-notch text-5xl animate-spin mb-4"></i>
			<h3>{% trans 'Thank you for your purchase'%}</h4>
			<div>
				{% trans 'We are confirming your payment, please dont refresh the page' %}
			</div>
		</div>
	</div>
{% endblock %}
{% block content %}
	<div class="md:hidden px-2 sm:px-4 w-full py-4 bg-primary-400 text-primary-bg collapsible cursor-pointer">
		<div class="flex justify-between self-center items-center max-w-screen-2xl m-auto">
			<div class="text-sm">
				<i class="fal fa-shopping-cart mr-2"></i>
				{% trans 'Show order' %}
			</div>
			<div>
				{{ cart.get_display_total_price }}
			</div>
		</div>
	</div>
	<div class="px-2 sm:px-4 w-full max-h-0 overflow-hidden duration-500 
			transition-all border-b border-gray-200 md:hidden">
		<div id="cartCheckoutTop">
		</div>
	</div>
	<div class="max-w-screen-2xl m-auto flex">
		<div class="w-full md:w-7/12 p-2 md:p-4 lg:p-8">
			<div class="text-xs mt-4 mb-8">
				<a class="link-primary" href="{% url 'cart:details' %}">
					{% trans 'Cart' %}
				</a>
				<i class="text-xs fal fa-chevron-right"></i>
				<a class="link-primary" href="{% url 'order:information' %}">
					{% trans 'Information' %}
				</a>
				<i class="xs fal fa-chevron-right"></i>
				<a class="link-primary" href="{% url 'order:shipping' %}">
					{% trans 'Shipping' %}
				</a>
				<i class="xs fal fa-chevron-right"></i>
				<strong>{% trans 'Payment' %}</strong>
			</div>
			<div class="mb-8">
				<div class="border border-gray-200 rounded px-4">
					<div class="flex justify-between items-center w-full py-4 border-b border-gray-200">
						<div class="flex flex-col sm:flex-row text-sm">
							<div class="w-24">
								{% trans 'Contact' %}
							</div>
							<div>
								{{ order.email }}
							</div>
						</div>
						<a class="link-primary text-xs" href="{% url 'order:information' %}">
							{% trans 'Change' %}
						</a>
					</div>
					<div class="flex justify-between items-center w-full py-4 border-b border-gray-200">
						<div class="flex flex-col sm:flex-row text-sm">
							<div class="w-24">
								{% trans 'Ship to' %}
							</div>
							<div>
								{{ order.address }}
								{% if order.address2 %}{{ order.address2 }}{% endif %},
								{{ order.postal_code }}
								{{ order.city }},
								{% if order.state %}{{ order.state }}{% endif %}
								{{ order.get_country_readable }}
							</div>
						</div>
						<a class="link-primary text-xs" href="{% url 'order:information' %}">
							{% trans 'Change' %}
						</a>
					</div>
					<div class="flex justify-between items-center w-full py-4">
						<div class="flex flex-col sm:flex-row text-sm">
							<div class="w-24">
								{% trans 'Method' %}
							</div>
							<div>
								{{ shipping_method.name }} - <strong>{{ shipping_method.get_display_price }}</strong>
							</div>
						</div>
						<a class="link-primary text-xs" href="{% url 'order:information' %}">
							{% trans 'Change' %}
						</a>
					</div>
				</div>
			</div>
			<div class="text-lg mb-2">
				{% trans 'Payment method' %}
			</div>
			<div id="payment-loading" class="border border-gray-200 rounded mb-4">
				<div class="animate-pulse">
					<div class="p-4 cursor-pointer border-b border-gray-200 flex justify-between select-none">
						<div class="h-6 bg-gray-400 rounded w-2/6"></div>
						<div class="h-6 bg-gray-400 rounded w-3/6"></div>
					</div>
					<div class="p-4 cursor-pointer select-none">
						<div class="h-6 bg-gray-400 rounded w-2/6"></div>
					</div>
				</div>
			</div>
			<div id="payment-real" class="border-t border-l border-r border-gray-200 rounded hidden mb-4">
				<div id="credit-card-tab" class="collapsible p-4 cursor-pointer border-b border-gray-200 flex justify-between select-none">
					<div>
						{% trans 'Credit card' %}
					</div>
					<div class="flex">
						<img class="credit-card-icon vertical-align-top"
							src="{% static 'order/img/visa.svg' %}"
							alt="visa">
						<img class="credit-card-icon vertical-align-top"
							src="{% static 'order/img/master.svg' %}"
							alt="master">
						<img class="credit-card-icon vertical-align-top"
							src="{% static 'order/img/amex.svg' %}"
							alt="amax">
						<img class="credit-card-icon vertical-align-top"
							src="{% static 'order/img/discover.svg' %}"
							alt="discover">
						<div class="flex items-center text-xs ml-2 select-none">
							{% trans 'and more ..' %}
						</div>
					</div>
				</div>
				<div class="stripe max-h-0 overflow-hidden duration-500 transition-all">
					<div class="flex self-center justify-center border-b border-gray-200 px-2 sm:px-8 py-4">
						<form id="payment-form" class="mt-4 w-full max-w-lg">
							{% csrf_token %}
							<div id="stripe-card-element">
							</div>
							<button id="submit" class="stripe">
								<div class="stripe-spinner hidden" id="stripe-spinner"></div>
								<span id="stripe-button-text">Pay</span>
							</button>
							<p id="stripe-card-error" role="alert"></p>
						</form>
					</div>
				</div>
				<div class="collapsible p-4 cursor-pointer border-b border-gray-200 flex justify-between select-none">
					<div>
						Paypal
					</div>
				</div>
				<div id="paypalPanel" class="max-h-0 overflow-hidden duration-500 transition-all">
					<div id="paypalContent" class="flex self-center justify-center px-2 sm:px-8 py-8 border-b border-gray-200">
						<div id="paypal-button-container" class="w-full max-w-lg z-1">
						</div>
						<!--script>
							paypal.Buttons().render('#paypal-button-container');
						</script-->
					</div>
				</div>
			</div>
			<div class="flex flex-col-reverse md:flex-row text-sm justify-between items-center">
				<a class="link-primary w-full md:w-auto py-4" href="{% url 'order:shipping' %}">
					<div class="text-center md:text-left">
						<i class="mr1 text-xs fal fa-chevron-left"></i> 
						{% trans 'Back to shipping method' %}
					</div>
				</a>
			</div>
		</div>
		<div id="cartCheckoutRight" class="hidden md:flex w-5/12 md:p-4 lg:p-8">
		</div>
	</div>
{% endblock %}
{% block extra_js %}
{% get_currency_code_paypal as currency_code_paypal %}
<script
	src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}&currency={{ currency_code_paypal }}">
</script>
<script src="https://js.stripe.com/v3/"></script>
<script>
	const paymentLoading = document.getElementById('payment-loading');
	const paymentReal = document.getElementById('payment-real');
	const errorMessage = '{% trans "There has been an error while trying to process your payment, please refresh the page and try again or contact our support" %}';
	const csrf = document.getElementById('payment-form').firstChild.nextElementSibling.value;
	const stripe = Stripe('{{ stripe_publishable_key }}');
	function showPaymentOverlay() {
		document.getElementById('paymentOverlay').classList.remove('hidden');
	}
	function hidePaymentOverlay() {
		document.getElementById('paymentOverlay').classList.add('hidden');
	}
	function initStripe() {
		let elements = stripe.elements();
		let style = {
			base: {
				color: "#32325d",
				fontFamily: 'Arial, sans-serif',
				fontSmoothing: "antialiased",
				fontSize: "16px",
				"::placeholder": {
					color: "#32325d"
				}
			},
			invalid: {
				fontFamily: 'Arial, sans-serif',
				color: "#fa755a",
				iconColor: "#fa755a"
			}
		};
		let card = elements.create("card", { style: style });
		card.mount("#stripe-card-element");
		card.on("change", function (event) {
			document.querySelector("button").disabled = event.empty;
			document.querySelector("#stripe-card-error").textContent = event.error ? event.error.message : "";
		});
		let form = document.getElementById("payment-form");
		form.addEventListener("submit", function(event) {
			event.preventDefault();
			payWithCard(stripe, card, '{{ stripe_payment_intent_client_secret }}');
		});
		setTimeout(() => {
			paymentLoading.classList.add('hidden');
			paymentReal.classList.remove('hidden');
			setTimeout(() => {
				document.getElementById('credit-card-tab').click();
			}, 100);
		}, 3000);
	}
	function sofortPayment() {
		stripe.confirmSofortPayment(
			'{{ stripe_payment_intent_client_secret }}',
			{
				payment_method: {
					sofort: {
						country: "AT"
					}
				},
				return_url: 'https://09584011c523.ngrok.io',
			}
		);
	}
	let payWithCard = function(stripe, card, clientSecret) {
		loading(true);
		stripe
			.confirmCardPayment(clientSecret, {
				payment_method: {
					card: card
				}
			})
			.then(function(result) {
				if (result.error) {
					if (result.error.code == 'payment_intent_unexpected_state') {
						showError('{% trans "Your checkout session has expired. Please reload the page." %}');
						location.reload();
					} else {
						loading(false);
						let errorMsg = document.querySelector("#stripe-card-error");
						errorMsg.textContent = errorMessage;
					}
				} else {
					orderComplete(result.paymentIntent.id);
				}
			});
	};
	let orderComplete = function(paymentIntentId) {
		showPaymentOverlay();
		loading(false);
		document.querySelector("button").disabled = true;
		fetch('{% url "order:stripe_verification" payment_intent_id="replace" %}'.replace('replace', paymentIntentId))
			.then(res => res.json())
			.then(function (response) {
				if (response['data']['success']) {
					window.location.href = response['data']['url'];
				} else {
					showError(errorMessage);
				}
			})
			.catch((error) => {
				hidePaymentOverlay();
				createFancyAlert('error', "{% trans 'Error' %}", errorMessage);
			});
	};
	let showError = function(errorMsgText) {
		createFancyAlert('error', '{% trans "Error" %}', errorMsgText);
		loading(false);
		let errorMsg = document.querySelector("#stripe-card-error");
		errorMsg.textContent = errorMsgText;
		hidePaymentOverlay();
	};
	let loading = function(isLoading) {
		if (isLoading) {
			document.querySelector("button").disabled = true;
			document.querySelector("#stripe-spinner").classList.remove("hidden");
			document.querySelector("#stripe-button-text").classList.add("hidden");
		} else {
			document.querySelector("button").disabled = false;
			document.querySelector("#stripe-spinner").classList.add("hidden");
			document.querySelector("#stripe-button-text").classList.remove("hidden");
		}
	};
	loadCart = false
	getCart();
	initStripe();
	paypal.Buttons({
			createOrder: function() {
				return '{{ paypal_order_id }}';
			}, 
			onApprove: function(data, actions) {
				showPaymentOverlay();
				return actions.order.capture().then(function(details) {
					fetch('{% url "order:paypal_verification" paypal_order_id="replace" %}'.replace('replace', data.orderID))
						.then(res => res.json())
						.then(function (response) {
							if (response['data']['success']) {
								window.location.href = response['data']['url'];
							} else {
								showError(errorMessage);
							}
						});
				});
			},
			onError: function (err) {
				console.log(err);
				showError(errorMessage);
			}
		}).render('#paypal-button-container');
	const paypalPanel = document.getElementById('paypalPanel');
	const paypalContent = document.getElementById('paypalContent');
	if (paypalContent) {
		const resizeObserver = new ResizeObserver(entries => {
			if (paypalPanel.style.maxHeight) {
				paypalPanel.style.maxHeight = (paypalPanel.scrollHeight + 50) + 'px';
			} else {
				paypalPanel.style.maxHeight = null;
			}
		});
		resizeObserver.observe(paypalContent);
	}
</script>
{% endblock %}