blog/urls.py
from django.urls import path

from blog import views


urlpatterns = [
	path('tagify_query/', views.tagify_query, name='tagify_query'),
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.contact_view, name='contact'),
]

webshop/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from home.views import home
from search import views as search_views

urlpatterns = i18n_patterns(
	path('', home, name=''),
	path('i18n/', include('django.conf.urls.i18n')),
	path('django-admin/', admin.site.urls),
	path('admin/', include(wagtailadmin_urls)),
	path('documents/', include(wagtaildocs_urls)),
	path('search/', search_views.search, name='search'),
	path('password-reset/complete/', 
		auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
		name='password_reset_complete'),
	path(_('home/'), include(('home.urls', 'home'), namespace='home')),
	path(_('account/'), include(('account.urls', 'account'), namespace='account')),
	path(_('blog/'), include(('blog.urls', 'blog'), namespace='blog')),
	path(_('cart/'), include(('cart.urls', 'cart'), namespace='cart')),
	path(_('contact/'), include(('contact.urls', 'contact'), namespace='contact')),
	path(_('coupon/'), include(('coupon.urls', 'coupon'), namespace='coupon')),
	path(_('newsletter/'), include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
	path(_('order/'), include(('order.urls', 'order'), namespace='order')),
	path(_('shop/'), include(('shop.urls', 'shop'), namespace='shop')),
	path(_('winwheel/'), include(('winwheel.urls', 'winwheel'), namespace='winwheel')),
	path('rosetta/', include('rosetta.urls')),
)



if settings.DEBUG:
	import debug_toolbar
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns = urlpatterns + i18n_patterns(
	# For anything not caught by a more specific rule above, hand over to
	# Wagtail's page serving mechanism. This should be the last pattern in
	# the list:
	path('', include(wagtail_urls)),

	# Alternatively, if you want Wagtail pages to be served from a subpath
	# of your site, rather than the site root:
	#    path("pages/", include(wagtail_urls)),
)

contact/models.py
import logging
from django.db import models
from django.db.utils import ProgrammingError
from django.utils.translation import gettext_lazy as _

from wagtail.core.models import Orderable

from modelcluster.models import ClusterableModel


logger = logging.getLogger('django')
recaptcha_public_key: str = None
recaptcha_private_key: str = None

class Setting(ClusterableModel, Orderable):
	key = models.CharField(max_length=255, db_index=True, unique=True)
	value = models.CharField(max_length=255, db_index=True)

	class Meta:
		verbose_name = 'Setting'
		verbose_name_plural = 'Settings'
		ordering = ['key']

	def __str__(self):
		return self.key

	@staticmethod
	def get_RECAPTCHA_PUBLIC_KEY() -> str:
		"""
		Get the maximum order quantity
		"""
		global recaptcha_public_key
		if recaptcha_public_key is None:
			try:
				recaptcha_public_key = Setting.objects.get(key='RECAPTCHA_PUBLIC_KEY').value
			except Setting.DoesNotExist:
				return 'None'
			except ProgrammingError:
				logging.error(_('Run python manage.py migrate'))
				return 'None'
			except Exception as e:
				return logging.error(str(e))
		return recaptcha_public_key

	@staticmethod
	def get_RECAPTCHA_PRIVATE_KEY() -> str:
		"""
		Get the maximum order quantity
		"""
		global recaptcha_private_key
		if recaptcha_private_key is None:
			try:
				recaptcha_private_key = Setting.objects.get(key='RECAPTCHA_PRIVATE_KEY').value
			except Setting.DoesNotExist:
				return 'None'
			except ProgrammingError:
				logging.error(_('Run python manage.py migrate'))
				return 'None'
			except Exception as e:
				return logging.error(str(e))
		return recaptcha_private_key

	def save(self, *args, **kwargs) -> None:
		super().save(*args, **kwargs)
		if self.key == 'RECAPTCHA_PUBLIC_KEY':
			global recaptcha_public_key
			recaptcha_public_key = self.value
		elif self.key == 'RECAPTCHA_PRIVATE_KEY':
			global recaptcha_private_key
			recaptcha_private_key = self.value


class Contact(ClusterableModel, Orderable):
	name = models.CharField(max_length=80)
	email = models.EmailField()
	message = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('created', )

	def __str__(self):
		return self.email

contact/forms.py
import logging
from smtplib import SMTPAuthenticationError

from django import forms
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _

from contact.models import Contact
from webshop.settings import base


logger = logging.getLogger('django')


class ContactForm(forms.ModelForm):
	name = forms.CharField(
		label=_('Name'),
		widget=forms.TextInput(
			attrs={
				'placeholder': _('Name')
			}
		),
	)
	email = forms.EmailField(
		label=_('Email'),
		widget=forms.TextInput(
			attrs={
				"type": "email",
				'placeholder': 'email@gmail.com'
			}
		),
	)
	message = forms.CharField(
		label=_('Message'),
		widget=forms.Textarea(
			attrs={
				'placeholder': 'Message'
			}
		),
	)

	class Meta:
		model = Contact
		fields = ('name', 'email', 'message', )

	def save(self, commit=True):
		instance = super(ContactForm, self).save(commit=False)
		try:
			send_mail(
				str(_('New message from webshop')),
				f'{instance.email} wrote: {instance.message}',
				base.EMAIL_HOST_USER,
				[base.EMAIL_HOST_USER],
				fail_silently=False,
			)
		except SMTPAuthenticationError as e:
			logger.error(_('New contact: ' + str(e)))
		if commit:
			instance.save()

contact/views.py
import json
import re
import requests

from django.contrib import messages
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from contact.models import Setting
from contact.forms import ContactForm


def contact_view(request):
	"""
	Contact view
	"""
	contact_form = ContactForm()
	if request.method == 'POST':
		if not request.POST['g-recaptcha-response']:
			messages.error(
				request,
				json.dumps({
					'data': {
						'title': str(_('Message not sent')),
						'innerHTML': str(_('Please complete the captcha')),
						'type': 'error'
					}
				})
			)
			return render(request, 'contact/contact.html', {
				'contact_form': ContactForm(),
				'site_key': Setting.get_RECAPTCHA_PUBLIC_KEY(),
			})
		data = {
			'response': request.POST['g-recaptcha-response'],
			'secret': Setting.get_RECAPTCHA_PRIVATE_KEY(),
		}
		resp = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
		result_json = resp.json()
		if not result_json.get('success'):
			messages.error(
				request,
				json.dumps({
					'data': {
						'title': str(_('Message not sent')),
						'innerHTML': str(_('We think that you are a robot')),
						'type': 'error'
					}
				})
			)
			return render(request, 'contact/contact.html', {
				'contact_form': ContactForm(),
				'site_key': Setting.get_RECAPTCHA_PUBLIC_KEY(),
			})
		contact_form = ContactForm(data=request.POST)
		if contact_form.is_valid():
			contact_form.save()
			messages.success(
				request,
				json.dumps({
					'data': {
						'title': str(_('Message sent')),
						'innerHTML': str(_('We received your message and will respond as soon as possible')),
						'type': 'success'
					}
				})
			)
		else:
			messages.error(
				request,
				json.dumps({
					'data': {
						'title': str(_('Message not sent')),
						'innerHTML': get_errors_from_form(contact_form),
						'type': 'error'
					}
				})
			)
	return render(request, 'contact/contact.html', {
		'contact_form': contact_form,
		'site_key': Setting.get_RECAPTCHA_PUBLIC_KEY(),
	})


def get_errors_from_form(form):
	errors = ""
	for k, v in form.errors.items():
		result = re.search('<li>(.*)</li>', str(v))
		errors = errors + result.group(1) + "\n"
		errors = errors.replace('&#39;', "'")
	return errors

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Contact' %}{% endblock %}

{% block content %}
<div class="p-2 sm:p-4 m-auto text-center max-w-4xl">
	<div class="md:text-4xl mt-8 mb-4 md:mt-16 md:mb-12">
		<h1 class="mb-6">{% trans 'Contact' %}</h2>
	</div>
  <div>
    {% if form.non_field_errors %}
    <div class="form-error-container mb-4">
      {% for error in form.non_field_errors %}
        {{ error|escape }}<br />
      {% endfor %}
    </div>
    {% endif %}
    <form action="{% url 'contact:contact' %}" method="post" class="text-left">
      <div class="mb-4">
				<div>
					<label class="font-bold" for="{{ contact_form.name.id_for_label }}">
						{% trans 'Name' %}
					</label>
				</div>
        <input id="{{ contact_form.name.id_for_label }}" name="{{ contact_form.name.html_name }}"
          placeholder="{% trans 'Name' %}" type="text" class="w-full border border-gray-400 p-3 rounded
					{% if contact_form.name.errors %}border-red-400{% else %}border-gray-400{% endif %}
					" required autofocus />
        {% if contact_form.name.errors %}
					<div class="text-sm text-red-400 text-left">
						{% for error in contact_form.name.errors %}
							{{ error|escape }}
						{% endfor %}
					</div>
        {% endif %}
      </div>
      <div class="mb-4">
				<div>
					<label class="font-bold" for="{{ contact_form.email.id_for_label }}">
						{% trans 'Email' %}
					</label>
				</div>
        <input id="{{ contact_form.email.id_for_label }}" name="{{ contact_form.email.html_name }}"
          placeholder="{% trans 'Email' %}" type="email" 
					class="w-full border p-3 rounded 
					{% if contact_form.email.errors %}border-red-400{% else %}border-gray-400{% endif %}" 
					required>
        {% if contact_form.email.errors %}
					<div class="text-sm text-red-400 text-left">
						{% for error in contact_form.email.errors %}
							{{ error|escape }}
						{% endfor %}
					</div>
        {% endif %}
      </div>
      <div class="mb-4">
				<div>
					<label class="font-bold" for="{{ contact_form.message.id_for_label }}">
						{% trans 'Message' %}
					</label>
				</div>
        <textarea id="{{ contact_form.message.id_for_label }}" name="{{ contact_form.message.html_name }}"
						placeholder="{% trans 'Message' %}" rows="10" class="w-full border border-gray-400 p-3 h-auto rounded
						{% if contact_form.message.errors %}border-red-400{% else %}border-gray-400{% endif %}"
						required></textarea>
        {% if contact_form.message.errors %}
					<div class="text-sm text-red-400 text-left">
						{% for error in contact_form.message.errors %}
							{{ error|escape }}
						{% endfor %}
					</div>
        {% endif %}
      </div>
      {% csrf_token %}
      <div class="flex flex-col justify-end">
				<div class="g-recaptcha mb-4 flex flex-row-reverse" data-sitekey="{{ site_key }}"></div>
				<!--input id="recaptcha-input" type="hidden" name="g-recaptcha-response" value=""/-->
				<button
					class="button-primary rounded py-4 px-6 text-center">
					{% trans 'Send message' %}
				</button>
      </div>
    </form>
  </div>
  <br />
</div>
<!--script src="https://www.google.com/recaptcha/api.js?render={{site_key}}"><script-->
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>
	setTimeout(() => {
		document.getElementById('g-recaptcha-response').setAttribute('required', 'true')
	}, 500)
</script>
<!--script>
  grecaptcha.ready(function() {
    grecaptcha.execute('{{site_key}}', {action: 'contactform'}).then(function(token) {
        document.getElementById('recaptcha-input').value = token;
    });
  });
</script-->
{% endblock %}

contact/templates/contact/contact_page.html
{% extends 'base.html' %}
{% load i18n %}
{% block head %}
{% load wagtailcore_tags %}
  <meta name="theme-color" content="rgb(38, 38, 38)"/>
  <meta name="description" content="{{ self.title }}"/>
{% endblock %}
{% block title %}{{ self.title }}{% endblock %}
{% block bodytag %}style="background-color: rgb(38, 38, 38); color: #ffffff"{% endblock %}
{% block content %}
<div class="pt-4 pl-2 pr-2 p-sm-4 m-auto mt-5 text-center max-width-small" style="color: #ffffff;">
  <h1 class="mb-5">{{ self.title }}</h2>
  <div>
    {% if form.non_field_errors %}
    <div class="form-error-container mb-4">
      {% for error in form.non_field_errors %}
        {{ error|escape }}<br />
      {% endfor %}
    </div>
		{% endif %}
    <form id="contact-form" action="{% pageurl page %}" method="post" class="text-left"
			onSubmit="e.preventDefault();">
			{% for field in form %}
				<div class="mb-4">
					<label class="font-weight-bold" for="{{ field.id_for_label }}">
						{{ field.label }}
					</label>
					{% if field.field.widget.template_name == 'django/forms/widgets/textarea.html' %}
						<textarea id="{{ field.id_for_label }}" 
							name="{{ field.html_name }}"
							placeholder="{% trans 'Hello' %}" 
							rows="10" 
							class="basic-form-input h-auto"
							{% if field.field.widget.is_required %}required{% endif %}>
						</textarea>
					{% else %}
						<input id="{{ field.id_for_label }}" 
							name="{{ field.html_name }}"
							placeholder="{{ field.help_text }}"
							type="{{ field.field.widget.input_type }}"
							class="basic-form-input"
							{% if field.field.widget.is_required %}required{% endif %}/>
					{% endif %}
					{% if field.errors %}
						<div class="field-error">
							{% for error in field.errors %}
								{{ error|escape }}
							{% endfor %}
						</div>
					{% endif %}
				</div>
			{% endfor %}
      {% csrf_token %}
      <div class="d-flex flex-row-reverse">
        <button class="btn btn-contact-border btn-lg">
          {{ self.submit_button_text }}
        </button>
      </div>
    </form>
  </div>
  <br />
</div>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>
	setTimeout(() => {
		document.getElementById('g-recaptcha-response').setAttribute('required', 'true')
	}, 500)
</script>
{% endblock %}